spring.application.name=demo1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/dormitory_management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=codegym
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.messages.basename=message
spring.messages.encoding=UTF-8
spring.flyway.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
MAIL_USER=yourmail@gmail.com
MAIL_PASS=app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.web.resources.static-locations=file:C:/upload-images/
